apiVersion: operator.openshift.io/v1
kind: KubeDescheduler
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  logLevel: Normal
  mode: {{ .Values.mode }}
  operatorLogLevel: Normal
  deschedulingIntervalSeconds: 3600
  profileCustomizations:
    devLowNodeUtilizationThresholds: Medium
    namespaces:
      excluded:
        - my-namespace
  observedConfig:
    servingInfo:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
      minTLSVersion: VersionTLS12
  profiles:
    - AffinityAndTaints
    - TopologyAndDuplicates
  managementState: Managed
  unsupportedConfigOverrides: null
