apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-crole
rules:
- apiGroups:
    - apps.3scale.net
  resources:
    - apimanagers
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - authentication.istio.io
    - config.istio.io
    - networking.istio.io
    - rbac.istio.io
    - security.istio.io
    - authentication.maistra.io
    - rbac.maistra.io
  resources:
    - '*'
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - monitoring.coreos.com
  resources:
    - alertmanagers
    - alertmanagers/finalizers
    - alertmanagerconfigs
    - prometheuses
    - prometheuses/finalizers
    - thanosrulers
    - thanosrulers/finalizers
    - servicemonitors
    - podmonitors
    - probes
    - prometheusrules
  verbs:
    - '*'
- apiGroups:
  - '*'
  resources:
    - deployments
    - services
    - serviceaccounts
    - secrets
    - clusterrole
    - clusterrolebinding
    - limitranges
    - networkpolicies
    - pods
  verbs:
    - '*'
- apiGroups:
    - 'apps'
  resources:
    - deployments
    - services
    - daemonsets
    - statefulsets
  verbs:
    - '*'
- apiGroups:
    - 'apiextensions.k8s.io'
  resources:
    - customresourcedefinitions
    - services
  verbs:
    - '*'
- apiGroups:
    - 'machineconfiguration.openshift.io'
  resources:
    - kubeletconfigs
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - 'broker.amq.io'
  resources:
    - activemqartemises
    - activemqartemisaddresses
    - activemqartemisscaledown
    - activemqartemissecurities
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - 'interconnectedcloud.github.io'
  resources:
    - interconnects
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - logging.openshift.io
  resources:
    - clusterloggings
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - tekton.dev
  resources:
    - pipelines
    - tasks
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - bitnami.com
  resources:
    - sealedsecrets
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - batch
  resources:
    - cronjobs
  verbs:
    - '*'