apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  namespace: openshift-gitops
spec:
  project: platform-gitops
  source:
    repoURL: 'https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/sealed-secrets.git'
    targetRevision: HEAD
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops