{{- if .Values.amq.enabled}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-broker-operator
  namespace: {{ .Values.amq.namespace | default "openshift-operators"}}
subjects:
- kind: ServiceAccount
  name: amq-broker-operator
  # you will have to deploy the operator into this namespace, whatever it is
  namespace: openshift-operators
roleRef:
  kind: ClusterRole
  name: amq-broker-operator
  apiGroup: rbac.authorization.k8s.io
  {{- end}}
