{{- if .Values.amq.enabled}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-broker-operator
  namespace: {{ .Values.amq.namespace | default "openshift-operators"}}
subjects:
- kind: ServiceAccount
  name: amq-broker-operator
roleRef:
  kind: Role
  name: amq-broker-operator
  apiGroup: rbac.authorization.k8s.io
  {{- end}}
