kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alerts-additional
rules:
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules