kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kyverno-additional
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - apps
    resources:
      - deployments