{{- if .Values.datagrid.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid
  namespace: {{ .Values.datagrid.namespace | default "openshift-operators" }}
spec:
  channel: 8.3.x
#  installPlanApproval: Automatic
  installPlanApproval: {{ .Values.datagrid.approvalPlan | default .Values.global.approvalPlan }}
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: datagrid-operator.v8.3.2
{{- end}}