{{- if .Values.jaegger.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: {{ .Values.jaegger.approvalPlan | default .Values.global.approvalPlan }}
  name: jaeger
  source: community-operators
  sourceNamespace: openshift-marketplace
{{- end}}

