{{- if .Values.microcks.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: microcks
  namespace: cicd
spec:
  channel: stable
  installPlanApproval: {{ .Values.microcks.approvalPlan | default .Values.global.approvalPlan }}
  name: microcks
  source: community-operators
  sourceNamespace: openshift-marketplace
{{- end}}

