{{- if .Values.rhsso.enabled}}
{{- range $key, $value := .Values.rhsso.namespaces }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: {{ $value }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel:  {{ $.Values.rhsso.approvalPlan | default "stable" }}
  installPlanApproval: {{ $.Values.rhsso.approvalPlan | default $.Values.global.approvalPlan }}
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}
{{- end}}
