apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ .Values.rhsso.namespace | default "iam" }}-rhsso
  namespace: {{ .Values.rhsso.namespace | default "iam" }}
spec:
  targetNamespaces:
    - {{ .Values.rhsso.namespace | default "iam" }}