{{- if .Values.rhsso.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: {{ .Values.rhsso.namespace | default "iam" }}
spec:
  channel:  {{ .Values.rhsso.approvalPlan | default "stable" }}
  installPlanApproval: {{ .Values.rhsso.approvalPlan | default .Values.global.approvalPlan }}
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}
