{{- if .Values.rhsso.enabled}}
{{- range $key, $value := .Values.rhsso.namespaces }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: {{ $value }}-rhsso
  namespace: {{ $value }}
spec:
  targetNamespaces:
    - {{ $value }}
{{- end}}
{{- end}}