{{- if .Values.istio.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators
spec:
  channel: {{ .Values.istio.approvalPlan | default "stable" }}
  installPlanApproval: {{ .Values.istio.approvalPlan | default .Values.global.approvalPlan }}
  name: servicemeshoperator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}