apiVersion: v1
kind: List
items:
  {{- range $namespace, $limitrangeval := .Values.limitrange.namespaces }}
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: limitrange-admin-binding
    subjects:
      - kind: ServiceAccount
        name: pipeline
        namespace: {{ $namespace }}
      - kind: ServiceAccount
        name: builder
        namespace: {{ $namespace }}
      - kind: ServiceAccount
        name: openshift-gitops-argocd-application-controller
        namespace: openshift-gitops
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: limitrange-admin
  {{- end }}
