#Rbac policy para dar visibilidad a proyectos de argo con los grupos de openshift
rbacPolicy:
  projects:
    - des-prueba

#Cluster role bindings para dar a argo permisos a la carta en ciertas aplicaciones de plataforma
sa:
  argoCrb:
    istio: true
    kyverno: true
    logging: true
    rhsso: true
    sealedsecrets: true
    tekton: true
  #Services accounts adicionales con sus rolebindings por namespace
  pipelines:
    - namespace: prueba-pipelines
      rbacNamespaces:
        - des-prueba
        - pre-prueba
        - uat-prueba
