sa:
  argo:
    namespaces:
      - cicd
      - istio-system
      - prueba-pipelines
  pipelines:
    - namespace: prueba-pipelines
      rbacNamespaces:
        - des-prueba
        - pre-prueba
        - uat-prueba
