#Cluster role bindings para dar a argo permisos a la carta en ciertas aplicaciones de plataforma
sa:
  argoCrb:
    istio: true
    kyverno: true
    logging: true
    rhsso: true
    sealedsecrets: true
    tekton: true

  pipelines:
    - namespace: prueba-pipelines
      rbacNamespaces:
        - des-prueba
        - pre-prueba
        - uat-prueba
