{{- if or .Values.project.enabled.des .Values.project.enabled.pro }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: application-monitoring
    role: alert-rules
  name: {{ $.Values.project.name }}-containerrestart-alert
  namespace: {{ $.Values.project.name }}
spec:
  groups:
  - name: containerrestart.rules
    rules:
    - alert: ContainerRestart
      annotations:
        description: |-
          {{` Pod {{$labels.namespace}}/{{$labels.pod}} restarting more than once times during last 5 minutes.
            VALUE = {{ $value }}
            LABELS: {{ $labels }} `}}
        summary: {{` Container {{ $labels.container }} in Pod {{$labels.namespace}}/{{$labels.pod}}
          restarting more than once times during last 5 minutes. `}}
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 1
      for: 1m
      labels:
        severity: warning-custom
{{- end }}