{{- if or .Values.project.enabled.des .Values.project.enabled.pro }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: application-monitoring
    role: alert-rules
  name: {{ $.Values.project.name }}-containermemoryusage-alert
  namespace: {{ $.Values.project.name }}
spec:
  groups:
  - name: containermemoryusage.rules
    rules:
    - alert: ContainerMemoryUsage
      annotations:
        description: |-
          {{` Container Memory usage is above 90%
            VALUE = {{ $value }}
            LABELS: {{ $labels }} `}}
        summary: {{` Container Memory usage (instance {{ $labels.instance }}) `}}
      expr: (sum(container_memory_working_set_bytes) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 90
      for: 2m
      labels:
        severity: warning-custom
{{- end }}