secret:
  name: token-tekton-pipe
  data:
    pass: bjgtb3NYZU55QVdQXzI0eWFmcVg=
    token: QlpDUjY2NTE6bjgtb3NYZU55QVdQXzI0eWFmcVg=
    user: QlpDUjY2NTE=

tenants:
  prueba:
    namespaces:
      - name: des-prueba
        displayName: Entorno de DES prueba
        limitRange:
          enabled: true
          limits:
            - type: Container
              max:
                cpu: '7'
                memory: 50Gi
              default:
                cpu: 300m
                memory: 400Mi
              defaultRequest:
                cpu: 300m
                memory: 400Mi
      - name: pre-prueba
        displayName: Entorno de PRE prueba
        limitRange:
          enabled: false
      - name: uat-prueba
        displayName: Entorno de UAT prueba
        limitRange:
          enabled: false
      - name: prueba-pipelines
        displayName: Pipelines para el entorno de prueba