selectorApp: sso
#Configuracion del realm
realm:
  id: ism
  name: ism
  displayName: Ism Realm
  enabled: true
  roles:
    - id: App
      name: App
#Configuracion de clientes
clients:
  - clientId: ism-appian
    name: ism-appian
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: 2ae3aa07-3bf7-49b0-b2d7-e3f95529171c
    redirectUris:
        - http://localhost/*
    webOrigins:
        - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
        access.token.lifespan: '"79200"'
        use.refresh.tokens: '"true"'
        backchannel.logout.session.required: '"true"'
        client.session.max.lifespan: '"79200"'
        client.session.idle.timeout: '"79200"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: ism
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
      - name: giss-proteccionespecial
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: proteccionEspecial
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-ambitos
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: ambitos
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: ambitos
          jsonType.label: String 
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: ism-apps
    name: ism-apps
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: 9e511c8b-993a-49fa-ac57-3b68860bfe77
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"1800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"1800"'
      client.session.idle.timeout: '"1800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: ism
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: ism-batch
    name: ism-batch
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: e230af90-4198-48a0-8759-21c15d0afc90
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"28800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"28800"'
      client.session.idle.timeout: '"28800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: proteccionEspecial
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          user.attribute: proteccionEspecial
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: ism
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: ism-ciudadano
    name: ism-ciudadano
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: dfd76c64-2870-41b0-8540-43a0c34675c2
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"7200"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"7200"'
      client.session.idle.timeout: '"7200"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: ism
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles-saml
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: saml-roles
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: saml-roles
          jsonType.label: String            
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: ism-pentaho
    name: ism-pentaho
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: d6c26f4f-cf48-4be6-84b1-d02c568d4e39
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"28800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"28800"'
      client.session.idle.timeout: '"28800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: proteccionEspecial
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          user.attribute: proteccionEspecial
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: ism
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
#Configuracion de usuarios
users:
  - username: ism-ismcensoembarcaciones
    userId: c05a22fe-d112-4455-832b-44ef6c47e28a
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-ismcensoembarcaciones","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-ismcensoembarcaciones
      temporary: false
    roles:
      - App
  - username: ism-ismembarcaciones
    userId: f495b5bd-4d38-434c-8e84-a9f24531bf72
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-ismembarcaciones","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-ismembarcaciones
      temporary: false
    roles:
      - App
  - username: ism-ismrevisionbotiquines
    userId: e352d2c6-5a02-4563-a72d-0ddd71bd25db
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-ismrevisionbotiquines","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-ismrevisionbotiquines
      temporary: false
    roles:
      - App
  - username: ism-ismwsab
    userId: f3f2f0ff-d4a0-4975-af48-5caf4f6d5e0e
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-ismwsab","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-ismwsab
      temporary: false
    roles:
      - App
  - username: ism-pcisbff
    userId: 6c6da189-9c62-4101-9714-ff8648fdb371
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-pcisbff","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-pcisbff
      temporary: false
    roles:
      - App
  - username: ism-pciscore
    userId: 287980f4-7bf1-49e3-894c-55828dd50a51
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-pciscore","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-pciscore
      temporary: false
    roles:
      - App
  - username: ism-pcisfam2revisionbotiquines
    userId: 601535b2-f14e-456c-ac0d-6beb83b90c43
    enabled: true
    emailVerified: false
    attributes:
      audit-data:
        - '{"ip":"127.0.0.1","dni":"ism-pcisfam2revisionesbotiquines","departamento":"AppAuth","idCiudadano":"null","tipoToken":"APLICATIVO"}'
      roles: 
        - '"null"'
    credentials:
      type: password
      value: ism-pcisfam2revisionbotiquines
      temporary: false
    roles:
      - App  