apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube-get-pods
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - create