kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-create-jobs
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sonarqube-create-jobs
