apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube-create-jobs
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - 'batch'
    resources:
      - jobs
    verbs:
      - get
      - watch
      - list
      - create
