kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-get-pods
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sonarqube-get-pods