apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube-exec-pods
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods/exec
    verbs:
      - get
      - watch
      - list
      - create