kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-additional
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - '*'
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - '*'
    apiGroups:
      - broker.amq.io
    resources:
      - activemqartemises
