kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: amq-additional-rb
  namespace: amq
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amq-additional
