kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-logging-cr
rules:
  - apiGroups:
      - logging.openshift.io
    resources:
      - clusterloggings
    verbs:
      - create
      - update
      - patch
      - delete