apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-application-controller-cr
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups:
    - monitoring.coreos.com
  resources:
    - alertmanagers
    - alertmanagers/finalizers
    - alertmanagerconfigs
    - prometheuses
    - prometheuses/finalizers
    - thanosrulers
    - thanosrulers/finalizers
    - servicemonitors
    - podmonitors
    - probes
    - prometheusrules
  verbs:
    - '*'
- apiGroups:
  - '*'
  resources:
    - projects
    - deployments
    - daemonsets
    - statefulsets
    - services
    - serviceaccounts
    - secrets
    - clusterrole
    - clusterrolebinding
    - limitranges
    - networkpolicies
    - pods
    - cronjobs
    - buildconfigs
    - imagestreams
  verbs:
    - '*'
- apiGroups:
    - 'apiextensions.k8s.io'
  resources:
    - customresourcedefinitions
    - services
  verbs:
    - '*'
- apiGroups:
    - 'machineconfiguration.openshift.io'
  resources:
    - kubeletconfigs
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - create
    - update
    - patch
    - delete
