kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-istio-cr
rules:
  - apiGroups:
      - authentication.istio.io
      - config.istio.io
      - networking.istio.io
      - rbac.istio.io
      - security.istio.io
      - authentication.maistra.io
      - rbac.maistra.io
    resources:
      - '*'
    verbs:
      - create
      - update
      - patch
      - delete