kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-rhsso-cr
rules:
  - apiGroups:
      - keycloak.org
    resources:
      - keycloaks
      - keycloakrealms
      - keycloakclients
      - keycloakusers
    verbs:
      - '*'