kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-tekton-cr
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - create
      - update
      - patch
      - delete