{{- if .Values.sa.argoCrb.kyverno }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-kyverno-crb
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: argocd-kyverno-cr
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
{{- end }}