kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crud-deploy-val-hsum
  namespace: val-hsum
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - deployments