{{- if .Values.tuned.global.enabled}}
  {{- if .Values.tuned.example.enabled}}
  # Este tuned profile se saca  con  oc get Tuned/default -o yaml -n openshift-cluster-node-tuning-operator
  # No puede ser editado (es gestionado por operador). Sin embargo se usa como plantilla
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: example
  namespace: openshift-cluster-node-tuning-operator
spec:

#  profile:
#    - data: |
#        [main]
#        summary=Custom OpenShift node profile for HPC compute workloads
#        include=openshift-node,hpc-compute
#      name: openshift-node-hpc-compute

  recommend:
    - match:
        - label: node-role.kubernetes.io/master
        - label: node-role.kubernetes.io/infra
      operand:
        debug: false
      priority: 30
      profile: openshift-control-plane
    - operand:
        debug: false
      priority: 40
      profile: openshift-node

  {{- end}}
  {{- end}}