apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    maistra.io/original-host: cicd-{{ $.Values.gateway.host }}
  labels:
    maistra.io/gateway-name: cudc-gateway
    maistra.io/gateway-namespace: cicd
  name: cicd-sonarqube-route
  namespace: cicd
spec:
  host: cicd-{{ $.Values.gateway.host }}
  port:
    targetPort: http
  to:
    kind: Service
    name: sonarqube-{{ $.Values.environment }}-sonarqube
  wildcardPolicy: None
