kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-routes
  namespace: cicd
rules:
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - '*'
