kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sonarqube-route
  namespace: cicd
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sonarqube-routes
