defaults:
  validation: audit
  background: 'false'
policies:
- name: disallow-latesttag
  namespace: des-cudc
- name: allowed-signedimages
  namespace: val-hsum
  validation: enforce
  parameters:
  - harbor.cudc.aws.comunidad.madrid*
- name: disallow-nodeport
  namespace: des-cudc
  validation: enforce
- name: require-requestlimit
  validation: enforce
  namespace: des-cudc
  parameters: 
    - openshift.io/build.name: "*"
    - dar.kyverno/exclude.require.reqlim: 'true'
- name: require-probes
  validation: enforce
  namespace: des-cudc
  parameters: 
    - openshift.io/build.name: "*"
    - dar.kyverno/exclude.require.probes: 'true'
- name: require-requestlimit
  validation: enforce
  namespace: val-cudc
  parameters: 
    - openshift.io/build.name: "*"
    - dar.kyverno/exclude.require.reqlim: 'true'
- name: require-probes
  validation: enforce
  namespace: val-cudc
  parameters: 
    - openshift.io/build.name: "*"
    - dar.kyverno/exclude.require.probes: 'true'
- name: limit-pipelineruns
  namespace: pipelines-hsum
  validation: enforce
  parameters:
    - 1  
- name: limit-pipelineruns
  namespace: pipelines-cudc
  validation: enforce
  parameters:
    - 3  
- name: limit-pipelineruns
  namespace: pipelines
  validation: enforce
  parameters:
    - 3  
- name: disallow-privilegedpod
  namespace: des-cudc
- name: disallow-privilegedpod
  namespace: val-cudc
- name: disallow-privilegedpod
  namespace: pipelines-cudc
- name: disallow-privilegedpod
  namespace: pipelines-hsum
- name: disallow-privilegedpod
  namespace: pipelines