kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: machineautoscaler
  namespace: openshift-machine-api
rules:
  - verbs:
      - create
      - patch
      - delete
    apiGroups:
      - autoscaling.openshift.io
    resources:
      - machineautoscalers
