{{- range $mesh := .Values.clusterMesh }}
{{- if and $mesh.serviceEntry $mesh.serviceEntry.namespaces  }}
{{- range $namespace, $selist := $mesh.serviceEntry.namespaces }}
{{- range $se := $selist }}

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: "{{ lower ( replace "." "-" (printf "se-%s" $se.host) ) }}"
  namespace: "{{- $namespace }}"
spec:
  hosts:
    - {{ $se.host }}
  location: MESH_EXTERNAL
  ports:
    - name: https
      number: 443
      protocol: TLS
  resolution: DNS

{{- end }}
{{- end }}
{{- end }}
{{- end }}