kind: ConfigMap
apiVersion: v1
metadata:
  name: extensions-script
data:
  preconfigure.sh: >
    # Script to copy the files from
    #'/opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository/' to
    #'/home/jboss/.m2/repository/'

    # NOTE: This is only a temporary workaround for RH SSO 7.5.0 GA when behind
    #a proxy or in offline mode. The script should no longer be necessary
    #starting from RH SSO 7.5.1.

    mkdir -pv /home/jboss/.m2/repository > /tmp/preconfigure.log 2>&1

    cp -vr /opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository/*
    /home/jboss/.m2/repository/ >> /tmp/preconfigure.log 2>&1

    ls -al /home/jboss/.m2/repository >> /tmp/preconfigure.log 2>&1
