{{- $policyname := "add-imagepullsecret" }}
{{- $defaults := .Values.defaults }}
{{- range $policy := .Values.policies}}
{{- if (eq $policy.name $policyname) }}
apiVersion: kyverno.io/v1
kind: {{- template "clusterOrNot" (dict "policy" $policy) }}
metadata:
{{- template "getNamespace" (dict "policy" $policy) }}
  name: {{ default $policyname $policy.custom_name }}
  annotations:
    dar.kyverno.template/file: {{$policyname}}
    dar.kyverno.policy/suitableforproduction: 'false'
    dar.kyverno.policy/category: Images
    dar.kyverno.policy/subject: Pod
    kyverno.io/minversion: 1.6.0
    dar.kyverno.policy/description: >-
      Images coming from certain registries require authentication in order to pull them,
      and the kubelet uses this information in the form of an imagePullSecret to pull
      those images on behalf of your Pod. This policy searches for images coming from a
      registry called `corp.reg.com` and, if found, will mutate the Pod to add an
      imagePullSecret called `my-secret`.      
    dar.kyverno.template/parameters: 'true'
    dar.kyverno.template/filter: 'true'  
      
spec:
  rules:
  - name: add-imagepullsecret
    match:
      any:
      - resources:
          kinds:
          - Pod
    mutate:
      patchStrategicMerge:
        spec:
          containers:
          - <(image): {{ $policy.filter }}
          imagePullSecrets:
          - name: {{ first $policy.parameters }}
  {{- end }}
---
{{- end }}  