apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: worker-harbor-registry-trust
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,ZG9ja...
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/containers/registries.d/harbor.cudc.aws.comunidad.madrid.yaml
        - contents:
            source: data:text/plain;charset=utf-8;base64,ewogI...
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/containers/policy.json
        - contents:
            source: data:text/plain;charset=utf-8;base64,LS0tLS...
            verification: {}
          filesystem: root
          mode: 420
          path: /etc/pki/developers/harbor-signer-key.pub
  osImageURL: ""