{{- range $key, $value := .Values.tenants }}
# Por cada tenant, recorremos sus ns
{{- range $clave, $valor := $value.namespaces }}
{{- if $valor.limitRange.enabled }}
kind: LimitRange
apiVersion: v1
metadata:
  name: limit-range
  namespace: {{ $valor.name }}
spec:
  limits:
    {{- toYaml $valor.limitRange.limits | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}