{{- range $key, $value := .Values.tenants }}
# Por cada tenant, recorremos sus ns
{{- range $clave, $valor := $value.namespaces }}
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: {{ $valor.name }}
  annotations:
    openshift.io/display-name: {{ $valor.displayName }}
---
{{- end}}
{{- end}}