{{- $root := . -}}
{{- range $key, $value := .Values.tenants }}
# Por cada tenant, recorremos sus ns
{{- range $clave, $valor := $value.namespaces }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $root.Values.secret.name }}
  namespace: {{ $valor.name }}
type: Opaque
data:
  {{- toYaml $root.Values.secret.data | nindent 2 }}
---
{{- end }}
{{- end }}