{{- range $namespace := .Values.nad.namespaces }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ $.Values.nad.name }}
  namespace: {{ $namespace }}
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "{{ $.Values.nad.name }}",
      "type": "ipvlan",
      "master": "{{ $.Values.nad.device }}",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "{{ $.Values.nad.range }}",
        "routes": {{ $.Values.nad.routes }}
      }
    }
---
{{- end}}
