kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: event-reader
rules:
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - get
      - watch
      - list
