{{- if .Values.amq.enabled}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/amq-broker-rhel8.openshift-operators: ''
  name: amq-broker-rhel8
  namespace: openshift-operators
spec:
  channel: {{ .Values.amq.channel | default "stable" }}
  installPlanApproval: {{ .Values.amq.approvalPlan | default .Values.global.approvalPlan }}
  name: amq-broker-rhel8
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end}}