{{- $policyname := "require-probes" }}
{{- $defaults := .Values.defaults }}
{{- range $policy := .Values.policies}}
{{- if (eq $policy.name $policyname) }}
apiVersion: kyverno.io/v1
kind: {{- template "clusterOrNot" (dict "policy" $policy) }}
metadata:
{{- template "getNamespace" (dict "policy" $policy) }}
  name: {{ default $policyname $policy.custom_name }}
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet
    dar.kyverno.policy/suitableforproduction: 'true'
    dar.kyverno.template/file: {{$policyname}}
    dar.kyverno.policy/category: Best Practices
    dar.kyverno.policy/subject: Pod
    dar.kyverno.policy/description: >-
      Liveness and readiness probes need to be configured to correctly manage a Pod's
      lifecycle during deployments, restarts, and upgrades. For each Pod, a periodic
      `livenessProbe` is performed by the kubelet to determine if the Pod's containers
      are running or need to be restarted. A `readinessProbe` is used by Services
      and Deployments to determine if the Pod is ready to receive network traffic.
      This policy validates that all containers have one of livenessProbe, readinessProbe,
      or startupProbe defined.    
    dar.kyverno.template/parameters: 'false'
    dar.kyverno.template/filter: 'false'   
          
spec:
  validationFailureAction: {{ default $defaults.validation $policy.validation }}
  background: {{ default $defaults.background $policy.background }}
  rules:
  - name: validate-probes
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Liveness, readiness are required for all containers."
      foreach:
      - list: request.object.spec.containers[]
        deny:
          conditions:
            all:
            - key: livenessProbe
              operator: AllNotIn
              value: "{{ printf "{{ element.keys(@)[] }}" | toString }}"
            - key: readinessProbe
              operator: AllNotIn
              value: "{{ printf "{{ element.keys(@)[] }}" | toString }}"
  {{- end }}
{{- end }}