# To add from a specific context
{{- $namespace := .Values.namespace }}
apiVersion: v1
kind: List
items:
  {{- range $address := .Values.addresses }}
  - apiVersion: broker.amq.io/v2alpha3
    kind: ActiveMQArtemisAddress
    metadata:
      name: {{ $address.addressName }}-amqaddress
      namespace: {{ $namespace }}
    spec:
      queueConfiguration:
        durable: {{ $address.queueConfiguration.durable | default true }}
        configurationManaged: {{ $address.queueConfiguration.configurationManaged | default false }}
        autoCreateAddress: {{ $address.queueConfiguration.autoCreateAddress | default false }}
        routingType: {{ $address.routingType }}
        {{- if $address.queueConfiguration.filterString }}
        filterString: {{ $address.queueConfiguration.filterString }}
        {{- end }}
      addressName: {{ $address.addressName }}
      queueName: {{ $address.queueName }}
      routingType: {{ $address.routingType }}
  {{- end}}