apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.brokers.namespace }}
spec:
  acceptors:
    - name: amqp
      protocols: amqp
      {{- if .Values.brokers.ssl.acceptors.sslSecret }}
      sslEnabled: true
      sslSecret: {{ .Values.brokers.ssl.acceptors.sslSecret }}
      port: 5671
      {{- else}}
      port: 5672
      {{- end}}
      {{- if .Values.brokers.authenticatePeer }}
      authenticatePeer : {{ .Values.brokers.authenticatePeer }}
      {{- end}}
#      verifyHost: false
      expose: true
  {{- if .Values.brokers.additionalAcceptors }}
  {{- toYaml .Values.brokers.additionalAcceptors | nindent 4 }}
  {{- end}}

  # Connectors define how to connect to other brokers if necesary
  {{- if .Values.brokers.connectors }}
  connectors:
    {{- toYaml .Values.brokers.connectors | nindent 4 }}
  {{- end}}

  adminPassword: {{ .Values.adminPassword | default "admin" }}
  adminUser: {{ .Values.adminUser | default "admin" }}

  console:
    {{- if .Values.brokers.ssl.console.sslSecret }}
    sslEnabled: true
    sslSecret: {{ .Values.brokers.ssl.console.sslSecret }}
    {{- end}}
    expose: true

  deploymentPlan:
    size: {{ .Values.brokers.replicaCount }}
    persistenceEnabled: true
    resources:
      {{- toYaml .Values.brokers.resources | nindent 6 }}
    messageMigration: true
    clustered: {{ .Values.clustered }}
    enableMetricsPlugin: true
    image: placeholder
    storage:
      size: 2Gi

  upgrades:
    enabled: true
    minor: false
  version: 7.10.0
