apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.brokers.namespace }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: console-jolokia
      scheme: https
  selector:
    matchLabels:
      ActiveMQArtemis: {{ .Values.appName }}
