kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.brokers.namespace }}
  labels:
    ActiveMQArtemis: {{ .Values.appName }}
spec:
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  internalTrafficPolicy: Cluster
  type: ClusterIP
  selector:
    ActiveMQArtemis: {{ .Values.appName }}
