kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-routes
  namespace: istio-system
rules:
  - verbs:
      - '*'
    apiGroups:
      - route.openshift.io
    resources:
      - '*'
