# Recorremos primero los tenants
{{- range $key, $value := .Values.tenants }}
# Por cada tenant, recorremos sus ns
{{- range $clave, $valor := $value.namespaces }}
kind: PeerAuthentication
apiVersion: security.istio.io/v1beta1
metadata:
  name: {{ $key  }}-istio-peers
  namespace: {{ $valor.name }}
  labels:
    app.kubernetes.io/instance: istio-des-val
spec:
  selector:
    matchLabels:
      {{- range $k,$v := $value.ra.matchLabels }}
      {{ $k }}: {{ $v }}
      {{- end }}
  mtls:
    mode: {{ $value.peerauth.mtlsmode}}
  portLevelMtls:
    '8081':
      mode: DISABLE
---
{{- end}}
{{- end}}
