# Recorremos primero los tenants
{{- range $key, $value := .Values.tenants }}
# Por cada tenant, recorremos sus ns
{{- range $clave, $valor := $value.namespaces }}
apiVersion: route.openshift.io/v1	
kind: Route	
metadata:	
  annotations:	
    maistra.io/original-host: {{ $valor.gatewayprefix }}-{{ $value.gateway.host }}
  labels:	
    app.kubernetes.io/instance: istio-{{ $.Values.env }}
    maistra.io/gateway-name: {{ $key }}-gateway	
    maistra.io/gateway-namespace: {{ $valor.name }}	
    maistra.io/generated-by: ior		
  name: {{ $valor.name }}-gateway-route
  namespace: istio-system	
spec:	
  host: {{ $valor.gatewayprefix }}.{{ $value.gateway.host }}
  port:	
    targetPort: https	
  tls:	
    termination: passthrough	
  to:	
    kind: Service	
    name: istio-ingressgateway	
    weight: 100	
  wildcardPolicy: None	
---
{{- end}}
{{- end}}