{{- if .Values.monitoring.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-prometheus-istio
  namespace: {{ .Values.controlplane.namespace }}
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: view
{{- end}}