{{- if .Values.verifyImages.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cosign-public-key
  namespace: {{ default "kyverno" .Values.verifyImages.secret_namespace }}
  annotations:
    dar.kyverno.template/file: Allowed Signed Images
    dar.kyverno.policy/category: Images
    dar.kyverno.policy/description: >-
      Los pods solamente hacen pull de imagenes que estén firmadas.     
    dar.kyverno.secret/title: Public Key for Cosign
    dar.kyverno.secret/description: To refernce in Policy and decrypt
type: Opaque
data:
{{- range $path, $bytes := .Files.Glob "publicKeys/allowed-signedimages/cosignpub.txt" }}
{{ "cosign.pub" | indent 2 }}: {{ tpl ($.Files.Get $path) $ | b64enc }}
{{- end }}
{{- end }}