selectorApp: sso
#Configuracion del realm
realm:
  id: fevi
  name: fevi
  displayName: fevi Realm
  enabled: true
  roles:
    - id: App
      name: App
#Configuracion de clientes
clients:
  - clientId: fevi-appian
    name: fevi-appian
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: 9e13d22b-c860-476b-b962-b5971410af67
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"79200"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"79200"'
      client.session.idle.timeout: '"79200"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: fevi
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
      - name: giss-proteccionespecial
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: proteccionEspecial
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-ambitos
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: ambitos
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: ambitos
          jsonType.label: String 
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: fevi-apps
    name: fevi-apps
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: e9b14f7f-0477-48fb-8a51-ff7ad2206f34
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"1800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"1800"'
      client.session.idle.timeout: '"1800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: fevi
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: fevi-batch
    name: fevi-batch
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: 13865649-3459-474b-a719-ce4c88136f33
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"28800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"28800"'
      client.session.idle.timeout: '"28800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: proteccionEspecial
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          user.attribute: proteccionEspecial
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: fevi
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: fevi-ciudadano
    name: fevi-ciudadano
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: 20f07361-357e-49aa-8502-038ec7c5b736
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"7200"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"7200"'
      client.session.idle.timeout: '"7200"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: fevi
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles-saml
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: saml-roles
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: saml-roles
          jsonType.label: String            
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone
  - clientId: fevi-pentaho
    name: fevi-pentaho
    rootUrl: http://localhost
    baseUrl: http://localhost
    surrogateAuthRequired: false
    enabled: true
    clientAuthenticatorType: client-secret
    secret: b3a136ec-b438-49c6-9956-8a9bccaa4238
    redirectUris:
      - http://localhost/*
    webOrigins:
      - http://localhost
    notBefore: 0
    bearerOnly: false
    consentRequired: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    publicClient: false
    #  description:  Keycloak client
    frontchannelLogout: false
    protocol: openid-connect
    attributes:
      access.token.lifespan: '"28800"'
      use.refresh.tokens: '"true"'
      backchannel.logout.session.required: '"true"'
      client.session.max.lifespan: '"28800"'
      client.session.idle.timeout: '"28800"'
    fullScopeAllowed: true
    nodeReRegistrationTimeout: -1
    protocolMappers:
      - name: proteccionEspecial
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          user.attribute: proteccionEspecial
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: proteccionEspecial
          jsonType.label: String
      - name: giss-tenant
        protocol: openid-connect
        protocolMapper: oidc-hardcoded-claim-mapper
        consentRequired: false
        config:
          claim.value: fevi
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: tenant
          jsonType.label: String
          access.tokenResponse.claim: '"false"'
      - name: giss-audit
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: audit-data
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: audit
          jsonType.label: String
      - name: giss-type
        protocol: openid-connect
        protocolMapper: oidc-usermodel-attribute-mapper
        consentRequired: false
        config:
          userinfo.token.claim: '"true"'
          user.attribute: giss-type
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: giss-type
          jsonType.label: String
      - name: giss-roles
        protocol: openid-connect
        protocolMapper: oidc-usermodel-realm-role-mapper
        consentRequired: false
        config:
          multivalued: '"true"'
          userinfo.token.claim: '"true"'
          id.token.claim: '"true"'
          access.token.claim: '"true"'
          claim.name: roles
          jsonType.label: String
    defaultClientScopes:
      - email
      - profile
      - roles
      - web-origins
    optionalClientScopes:
      - address
      - microprofile-jwt
      - offline_access
      - phone

