apiVersion: v1
kind: List
items:
  {{- range $alert := .Values.alerts }}
  - apiVersion: monitoring.coreos.com/v1
    kind: PrometheusRule
    metadata:
      name: {{ $alert.name }}
      namespace: {{ $alert.namespace }}
      labels:
        openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
    spec:
      groups:
      {{- toYaml $alert.groups | nindent 6 }}
  {{- end }}
