kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: HorizontalPodAutoscaler
  namespace: pro-ees
rules:
  - verbs:
      - create
      - patch
      - delete
    apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
