{{- $policyname := "disallow-deprecatedapis" }}
{{- $defaults := .Values.defaults }}
{{- range $policy := .Values.policies}}
{{- if (eq $policy.name $policyname) }}
apiVersion: kyverno.io/v1
kind: {{- template "clusterOrNot" (dict "policy" $policy) }}
metadata:
{{- template "getNamespace" (dict "policy" $policy) }}
  name: {{ default $policyname $policy.custom_name }}
  annotations:
    dar.kyverno.template/file: {{$policyname}}
    dar.kyverno.policy/category: Other
    dar.kyverno.policy/suitableforproduction: 'false'
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.20"
    dar.kyverno.policy/subject: ClusterRole,ClusterRoleBinding,Role,RoleBinding,RBAC
    dar.kyverno.policy/description: >-
      OpenShift APIs are sometimes deprecated and removed after a few releases.
      As a best practice, older API versions should be replaced with newer versions.
      This policy validates for APIs that are deprecated or scheduled for removal.
      Note that checking for some of these resources may require modifying the Kyverno
      ConfigMap to remove filters.          
    dar.kyverno.template/parameters: 'true'
    dar.kyverno.template/filter: 'false'    
         
spec:
  validationFailureAction: {{ default $defaults.validation $policy.validation }}
  background: {{ default $defaults.background $policy.background }}
  rules:
  - name: check-deprecated-apis
    match:
      any:
      - resources:
          kinds:
          {{- range $policy.parameters }}
          - {{ . }}
          {{- end }}
    validate:
      message: "{{ printf "{{ request.object.apiVersion }}/{{ request.object.kind }} is deprecated."| toString }}"
      deny: {}
  {{- end }}
---
{{- end }}  