{{- range $key, $value := .Values.tenants }}
{{- if $value.createApplications }}
# Por cada tenant, recorremos sus apps
{{- range $clave, $valor := $value.projects }}
{{- range $app, $appValue := $valor.apps }}
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ $appValue.name }}
  namespace: openshift-gitops
spec:
  project: {{ $valor.name }}
  source:
    repoURL: 'https://github.com/NTTData-HybridCloud/gitops-apps'
    targetRevision: master
    path: '{{ $appValue.folder }}'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ $appValue.namespace }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}