{{- range $key, $value := .Values.tenants }}
{{- if $value.createApplications }}
# Por cada tenant, recorremos sus projects
{{- range $clave, $valor := $value.projects }}
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: {{ $valor.name }}
  namespace: openshift-gitops
spec:
  description: group for application deployment
  destinations:
    - name: in-cluster
      namespace: openshift-gitops
      server: 'https://kubernetes.default.svc'
{{- range $namespace, $namespaceValue := $valor.namespaces }}
    - name: in-cluster
      namespace: {{ $namespaceValue }}
      server: 'https://kubernetes.default.svc'
{{- end }}
  sourceRepos:
  - 'https://github.com/NTTData-HybridCloud/gitops-apps'
---
{{- end }}
{{- end }}
{{- end }}