{{- $policyname := "disallow-manualtaskrun" }}
{{- $defaults := .Values.defaults }}
{{- range $policy := .Values.policies}}
{{- if (eq $policy.name $policyname) }}
apiVersion: kyverno.io/v1
kind: {{- template "clusterOrNot" (dict "policy" $policy) }}
metadata:
{{- template "getNamespace" (dict "policy" $policy) }}
  name: {{ default $policyname $policy.custom_name }}
  annotations:
    dar.kyverno.template/file: {{$policyname}}
    dar.kyverno.policy/suitableforproduction: 'true'
    dar.kyverno.policy/category: Tekton
    dar.kyverno.policy/subject: TaskRun
    kyverno.io/kyverno-version: 1.7.1
    kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    dar.kyverno.policy/description: "Prohibe crear taskRuns a mano, solo puede hacerlo Tekton"
    dar.kyverno.template/parameters: 'false'
    dar.kyverno.template/filter: 'false' 
     
spec:
  validationFailureAction: {{ default $defaults.validation $policy.validation }}
  background: false
  rules:
  - name: check-taskrun-user
    match:
      any:
      - resources:
          kinds:
            - TaskRun
    exclude:
      any:
      - subjects:
        - kind: User 
          name: "system:serviceaccount:tekton-pipelines:tekton-pipelines-controller"
    preconditions:
      all:
      - key: "{{ printf "{{ request.operation || 'BACKGROUND' }}" | toString }}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: Creating a TaskRun is not allowed.
      deny: {}
  {{- end }}
{{- end }} 