{{- range $key, $value := .Values.tenants }}
{{- if $value.createApplications }}
# Por cada tenant, recorremos sus apps
{{- range $clave, $valor := $value.projects }}
{{- range $namespace, $namespaceValue := $valor.namespaces }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $namespaceValue }}-pipelines-edit
  namespace: {{ $namespaceValue }}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ $value.name }}-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
