apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: {{ .Values.influxdb.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Values.influxdb.name }}
  ports:
    - name: http-influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
