apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: influxdb
  labels:
    app: {{ .Values.influxdb.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  to:
    kind: Service
    name: influxdb
    weight: 100
  port:
    targetPort: 8086
  wildcardPolicy: None



